<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

/**
 * @var array<string,object>    $efps           family parts which can be selected and eventually be sorted
 * @var string                  $title
 * @var string                  $description
 * @var boolean                 $uses_sorting   can the family parts be sorted?
 * @var boolean                 $show_filter_options
 * @var int                     $show_empty_block
 * @var boolean                 $show_short_name
 * @var boolean                 $show_labels
 * @var boolean                 $show_parameters
 * @var boolean                 $use_compact_design
 * @var boolean                 $show_summary
 * @var boolean                 $count_partner_chains
 * @var boolean                 $use_clippings_cart
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>
<p><?= $description ?></p>

<div class="hh-extended-family mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">
		
        <h3><?= I18N::translate('In which sequence should the parts of the extended family be shown?') ?></h3>
        <table class="table table-bordered wt-table-menu">
            <thead>
                <tr>
                    <th><?= I18N::translate('Family part (generation relative to proband)') ?></th>
                    <th class="text-center"><?= I18N::translate('Enabled') ?></th>
                    <?php if ($uses_sorting) : ?>
                      <th class="text-center"><?= I18N::translateContext('as in "Move up"', 'Move') ?></th>
                      <th class="text-center"><?= I18N::translateContext('as in "Move down"', 'Move') ?></th>
                    <?php endif ?>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($efps as $efp => $value) : ?>
                    <tr>
                        <th scope="col">
                            <input type="hidden" name="order[]" value="<?= $efp ?>">
                            <span title="<?= $value->name ?>">
                                <?= $value->name . ' (' . $value->generation . ')' ?>
                            </span>                          
                        </th>

                        <td class="text-center">
                            <label class="d-block">
                                <input type="checkbox" name="status-<?= $efp ?>" id="status-<?= $efp ?>" <?= ($value->enabled == 'on') ? 'checked' : '' ?>>
                                <span class="sr-only">
                                    <?= I18N::translate('Enabled') ?>
                                </span>
                            </label>
                        </td>

                        <?php if ($uses_sorting) : ?>
                            <td class="move up text-center">
                                <a href="#" title="<?= I18N::translate('Move up') ?>">
                                    <?= view('icons/arrow-up') ?>
                                </a>
                            </td>
                            <td class="move down text-center">
                                <a href="#" title="<?= I18N::translate('Move down') ?>">
                                    <?= view('icons/arrow-down') ?>
                                </a>
                            </td>
                        <?php endif ?>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        
        <h3><?= I18N::translate('Show options to filter the results?') ?></h3>
        <p><?= I18N::translate('This allows a user to filter the members of the extended family by gender and if they are alive or dead.') ?></p>
        <!-- show filter options -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show filter options') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show_filter_options', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$show_filter_options]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Should a summary block be shown?') ?></h3>
        <p><?= I18N::translate('The summary contains information about the extended family in total.') ?></p>
        <!-- show summary block -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show summary') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show_summary', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$show_summary]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('How should empty parts of extended family be presented?') ?></h3>
        <!-- show empty block -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show empty block') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/select', ['name' => 'show_empty_block', 'options' => [I18N::translate('yes, always at standard location'), I18N::translate('no, but collect messages about empty blocks at the summary block'), I18N::translate('never')], 'selected' => (int)$show_empty_block]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Count the members of the partner chains as members of the extended family?') ?></h3>
        <p>
            <?= I18N::translate('If you select "no", then the additional members in the partner chains will not be counted to the total number of individuals in the extended family.') ?>
            <?= I18N::translate('And these persons and families will be not selected when a user decides to copy the extended family to the clippings cart.') ?>
            <?= I18N::translate('But even in this case, you can copy these persons and families to the clippings cart by using a special menu topic of the custom module "enhanced clippings cart": "add partner chains for an individual".') ?>
            <?= I18N::translate('This is only relevant if you have chosen in the above table, that the partner chains should be shown as a part of the extended family.') ?>
        </p>
        <!-- count partner chain members as members of extended family -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Include them') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'count_partner_chains', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$count_partner_chains]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Show name of proband as short name or as full name?') ?></h3>
        <p><?= I18N::translate('The short name is based on the probands Rufname or nickname. If these are not available, the first of the given names is used, if one is given. Otherwise the last name is used.') ?></p>
        <!-- nice_name -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show short name') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show_short_name', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$show_short_name]) ?>
                </div>
            </div>
        </fieldset>
        
        <h3><?= I18N::translate('Show labels in special situations?') ?></h3>
        <p><?= I18N::translate('Labels (or stickers) are used for example for adopted persons or foster children.') ?></p>
        <!-- show labels -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show labels') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show_labels', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$show_labels]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Show parameters of extended family part?') ?></h3>
        <p><?= I18N::translate('Display of additional information for each part of the extended family, such as the generation shift and the coefficient of relationship, which is a measure of the degree of consanguinity.') ?></p>
        <!-- show parameters of family parts -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show parameters') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'show_parameters', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$show_parameters]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Use the compact design?') ?></h3>
        <p><?= I18N::translate('The compact design only shows the name and life span for each person. The enriched design also shows a photo (if this is activated for this tree) as well as birth and death information.') ?></p>
        <!-- use compact design -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Use the compact design') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'use_compact_design', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$use_compact_design]) ?>
                </div>
            </div>
        </fieldset>

        <h3><?= I18N::translate('Show a button "copy to clippings cart"?') ?></h3>
        <p><?= I18N::translate('This allows a user to copy all members of the extended family to the clippings cart.') ?></p>
        <!-- use button clippings cart -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Show button') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'use_clippings_cart', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$use_clippings_cart]) ?>
                </div>
            </div>
        </fieldset>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>

<?php View::push('javascript') ?>
<script>
  $('.wt-table-menu td.move').click(function () {
      var row = $(this).closest('tr');

      if ($(this).hasClass('up')) {
          row.prev().before(row);
      } else {
          row.next().after(row);
      }

      return false;
  });
</script>
<?php View::endpush() ?>

<?php View::push('styles') ?>
<style>
    .wt-table-menu tr:first-child .wt-icon-arrow-up {
        display:none;
    }
    .wt-table-menu tr:last-child .wt-icon-arrow-down {
        display:none;
    }
</style>
<?php View::endpush() ?>