<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="hh-extended-family mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">
		
        <h3><?= I18N::translate('Are these parts of the extended family to be shown?') ?></h3>
        <!-- grandparents -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Grandparents') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'grandparents', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$grandparents]) ?>
                </div>
            </div>
        </fieldset>
        <!-- parents -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Parents') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'parents', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$parents]) ?>
                </div>
            </div>
        </fieldset>
		<!-- uncles and aunts -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Uncles and Aunts') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'uncles_and_aunts', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$uncles_and_aunts]) ?>
                </div>
            </div>
        </fieldset>
        <!-- siblings -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Siblings') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'siblings', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$siblings]) ?>
                </div>
            </div>
        </fieldset>
        <!-- spouses -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Partners') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'partners', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$partners]) ?>
                </div>
            </div>
        </fieldset>
		<!-- cousins -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Cousins') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'cousins', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$cousins]) ?>
                </div>
            </div>
        </fieldset>
        <!-- nephews and nieces -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Nephews and Nieces') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'nephews_and_nieces', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$nephews_and_nieces]) ?>
                </div>
            </div>
        </fieldset>
        <!-- children -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Children') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'children', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$children]) ?>
                </div>
            </div>
        </fieldset>
        <!-- grandchildren -->
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-3">
                    <?= I18N::translate('Grandchildren') ?>
                </legend>
                <div class="col-sm-9">
                    <?= view('components/radios-inline', ['name' => 'grandchildren', 'options' => [I18N::translate('yes'), I18N::translate('no')], 'selected' => (int)$grandchildren]) ?>
                </div>
            </div>
        </fieldset>
		
        
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>

