<?php

	use Fisharebest\Webtrees\Functions\FunctionsPrintFacts;
	use Fisharebest\Webtrees\I18N;
	use Fisharebest\Webtrees\View;

 ?>
 
<div class="wt-tab-hh-extended-family py-4">
    <?php if ($extfam_obj->efp->allCount > 0): ?>
        <?php if ( $extfam_obj->config->showFamilyPart['grandparents'] ): ?>
            <div class="hh-extended-family-grandparents">
				<?php if (($extfam_obj->efp->Grandparents->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Grandparents') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Grandparents->allCount): ?>
                    <?php if ($extfam_obj->efp->Grandparents->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Grandparents->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one grandmother recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Grandparents->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one grandfather recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one grandparent recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Grandparents->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d grandmother recorded.',  '%2$s has %1$d grandmothers recorded.', $extfam_obj->efp->Grandparents->femaleCount, $extfam_obj->efp->Grandparents->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Grandparents->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d grandfather recorded.', '%2$s has %1$d grandfathers recorded.', $extfam_obj->efp->Grandparents->maleCount, $extfam_obj->efp->Grandparents->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d grandfather and ', '%2$s has %1$d grandfathers and ', $extfam_obj->efp->Grandparents->maleCount, $extfam_obj->efp->Grandparents->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d grandmother recorded (%d in total).', '%d grandmothers recorded (%d in total).', $extfam_obj->efp->Grandparents->femaleCount, $extfam_obj->efp->Grandparents->femaleCount, $extfam_obj->efp->Grandparents->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php if ($extfam_obj->efp->Grandparents->fathersFamilyCount): ?>
                            <div id="extended_family_f">
                                <h4><?= I18N::translate('Father\'s family (%d)', $extfam_obj->efp->Grandparents->fathersFamilyCount) ?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Grandparents->fatherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Grandparents->fathersAndMothersFamilyCount): ?>
                            <div id="extended_family_fm">
                                <h4><?= I18N::translate('Father\'s and Mother\'s family (%d)', $extfam_obj->efp->Grandparents->fathersAndMothersFamilyCount)?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Grandparents->fatherAndMotherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Grandparents->mothersFamilyCount): ?>
                            <div id="extended_family_m">
                                <h4><?= I18N::translate('Mother\'s family (%d)', $extfam_obj->efp->Grandparents->mothersFamilyCount) ?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Grandparents->motherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no grandparents recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>

        <?php if ( $extfam_obj->config->showFamilyPart['parents'] ): ?>
            <div class="hh-extended-family-parents">
				<?php if (($extfam_obj->efp->Parents->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Parents') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Parents->allCount): ?>
                    <?php if ($extfam_obj->efp->Parents->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Parents->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one mother recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Parents->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one father recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one parent recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Parents->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d mother recorded.',  '%2$s has %1$d mothers recorded.', $extfam_obj->efp->Parents->femaleCount, $extfam_obj->efp->Parents->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Parents->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d father recorded.', '%2$s has %1$d fathers recorded.', $extfam_obj->efp->Parents->maleCount, $extfam_obj->efp->Parents->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d father and ', '%2$s has %1$d fathers and ', $extfam_obj->efp->Parents->maleCount, $extfam_obj->efp->Parents->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d mother recorded (%d in total).', '%d mothers recorded (%d in total).', $extfam_obj->efp->Parents->femaleCount, $extfam_obj->efp->Parents->femaleCount, $extfam_obj->efp->Parents->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php if ($extfam_obj->efp->Parents->fathersFamilyCount): ?>
                            <div id="extended_family_f">
                                <h4><?= I18N::translate('Father\'s family (%d)', $extfam_obj->efp->Parents->fathersFamilyCount) ?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Parents->fatherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Parents->fathersAndMothersFamilyCount): ?>
                            <div id="extended_family_fm">
                                <h4><?= I18N::translate('Father\'s and Mother\'s family (%d)', $extfam_obj->efp->Parents->fathersAndMothersFamilyCount)?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Parents->fatherAndMotherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Parents->mothersFamilyCount): ?>
                            <div id="extended_family_m">
                                <h4><?= I18N::translate('Mother\'s family (%d)', $extfam_obj->efp->Parents->mothersFamilyCount) ?></h4>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->Parents->motherFamily as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no parents recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        <?php if ( $extfam_obj->config->showFamilyPart['uncles_and_aunts'] ): ?>
            <div class="hh-extended-family-uncles-aunts">
				<?php if (($extfam_obj->efp->UnclesAunts->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Uncles and Aunts') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->UnclesAunts->allCount): ?>
                    <?php if ($extfam_obj->efp->UnclesAunts->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->UnclesAunts->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one aunt recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->UnclesAunts->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one uncle recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one uncle or aunt recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->UnclesAunts->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d aunt recorded.',  '%2$s has %1$d aunts recorded.', $extfam_obj->efp->UnclesAunts->femaleCount, $extfam_obj->efp->UnclesAunts->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->UnclesAunts->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d uncle recorded.', '%2$s has %1$d uncles recorded.', $extfam_obj->efp->UnclesAunts->maleCount, $extfam_obj->efp->UnclesAunts->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d uncle and ', '%2$s has %1$d uncles and ', $extfam_obj->efp->UnclesAunts->maleCount, $extfam_obj->efp->UnclesAunts->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d aunt recorded (%d in total).', '%d aunts recorded (%d in total).', $extfam_obj->efp->UnclesAunts->femaleCount, $extfam_obj->efp->UnclesAunts->femaleCount, $extfam_obj->efp->UnclesAunts->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php if ($extfam_obj->efp->UnclesAunts->fathersFamilyCount): ?>
                            <div id="extended_family_f">
                                <h4><?= I18N::translate('Father\'s family (%d)', $extfam_obj->efp->UnclesAunts->fathersFamilyCount) ?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->UnclesAunts->fatherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->UnclesAunts->fathersAndMothersFamilyCount): ?>
                            <div id="extended_family_fm">
                                <h4><?= I18N::translate('Father\'s and Mother\'s family (%d)', $extfam_obj->efp->UnclesAunts->fathersAndMothersFamilyCount)?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->UnclesAunts->fatherAndMotherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->UnclesAunts->mothersFamilyCount): ?>
                            <div id="extended_family_m">
                                <h4><?= I18N::translate('Mother\'s family (%d)', $extfam_obj->efp->UnclesAunts->mothersFamilyCount) ?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->UnclesAunts->motherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no uncles or aunts recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        
        <?php if ( $extfam_obj->config->showFamilyPart['siblings'] ): ?>
            <div class="hh-extended-family-siblings">
				<?php if (($extfam_obj->efp->Siblings->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Siblings') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Siblings->allCount): ?>
                    <?php if ($extfam_obj->efp->Siblings->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Siblings->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one sister recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Siblings->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one brother recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one brother or sister recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Siblings->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d sister recorded.',  '%2$s has %1$d sisters recorded.', $extfam_obj->efp->Siblings->femaleCount, $extfam_obj->efp->Siblings->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Siblings->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d brother recorded.', '%2$s has %1$d brothers recorded.', $extfam_obj->efp->Siblings->maleCount, $extfam_obj->efp->Siblings->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d brother and ', '%2$s has %1$d brothers and ', $extfam_obj->efp->Siblings->maleCount, $extfam_obj->efp->Siblings->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d sister recorded (%d in total).', '%d sisters recorded (%d in total).', $extfam_obj->efp->Siblings->femaleCount, $extfam_obj->efp->Siblings->femaleCount, $extfam_obj->efp->Siblings->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php foreach ($extfam_obj->efp->Siblings->families as $famobj): ?>
                            <div id="extended_family_g">
                                
                                <?php    $i = 1; ?>
                                <?php  foreach ($famobj->members as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no siblings recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        <?php if ( $extfam_obj->config->showFamilyPart['partners'] ): ?>
            <div class="hh-extended-family-partners">
				<?php if (($extfam_obj->efp->Partners->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Partners') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Partners->allCount): ?>
                    <?php if ($extfam_obj->efp->Partners->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Partners->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one female partner recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Partners->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one male partner recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one partner recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Partners->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d female partner recorded.',  '%2$s has %1$d female partners recorded.', $extfam_obj->efp->Partners->femaleCount, $extfam_obj->efp->Partners->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Partners->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d male partner recorded.', '%2$s has %1$d male partners recorded.', $extfam_obj->efp->Partners->maleCount, $extfam_obj->efp->Partners->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d male partner and ', '%2$s has %1$d male partners and ', $extfam_obj->efp->Partners->maleCount, $extfam_obj->efp->Partners->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d female partner recorded (%d in total).', '%d female partners recorded (%d in total).', $extfam_obj->efp->Partners->femaleCount, $extfam_obj->efp->Partners->femaleCount, $extfam_obj->efp->Partners->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php foreach ($extfam_obj->efp->Partners->families as $famobj): ?>
                            <div id="extended_family_g">
                                
                                <?php    $i = 1; ?>
                                <?php  foreach ($famobj->members as $indi) : ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no partners recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        <?php if ( $extfam_obj->config->showFamilyPart['cousins'] ): ?>
            <div class="hh-extended-family-cousins">
				<?php if (($extfam_obj->efp->Cousins->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Cousins') ?></h2>
				<?php endif ?>					
                <?php if ($extfam_obj->efp->Cousins->allCount): ?>
                    <?php if ($extfam_obj->efp->Cousins->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Cousins->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one female first cousin recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Cousins->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one male first cousin recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one first cousin recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Cousins->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d female first cousin recorded.',  '%2$s has %1$d female first cousins recorded.', $extfam_obj->efp->Cousins->femaleCount, $extfam_obj->efp->Cousins->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Cousins->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d male first cousin recorded.', '%2$s has %1$d male first cousins recorded.', $extfam_obj->efp->Cousins->maleCount, $extfam_obj->efp->Cousins->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d male first cousin and ', '%2$s has %1$d male first cousins and ', $extfam_obj->efp->Cousins->maleCount, $extfam_obj->efp->Cousins->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d female first cousin recorded (%d in total).', '%d female first cousins recorded (%d in total).', $extfam_obj->efp->Cousins->femaleCount, $extfam_obj->efp->Cousins->femaleCount, $extfam_obj->efp->Cousins->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php if ($extfam_obj->efp->Cousins->fathersFamilyCount): ?>
                            <div id="extended_family_f">
                                <h4><?= I18N::translate('Father\'s family (%d)', $extfam_obj->efp->Cousins->fathersFamilyCount) ?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->Cousins->fatherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Cousins->fathersAndMothersFamilyCount): ?>
                            <div id="extended_family_fm">
                                <h4><?= I18N::translate('Father\'s and Mother\'s family (%d)', $extfam_obj->efp->Cousins->fathersAndMothersFamilyCount)?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->Cousins->fatherAndMotherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                        <?php if ($extfam_obj->efp->Cousins->mothersFamilyCount): ?>
                            <div id="extended_family_m">
                                <h4><?= I18N::translate('Mother\'s family (%d)', $extfam_obj->efp->Cousins->mothersFamilyCount) ?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php  foreach ($extfam_obj->efp->Cousins->motherFamily as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                        <span class="extended_family_pedi"><?= $module_obj->getChildLabel($indi) ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no first cousins recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        <?php if ( $extfam_obj->config->showFamilyPart['nephews_and_nieces'] ): ?>
            <div class="hh-extended-family-nephews-nieces">
				<?php if (($extfam_obj->efp->NephewsNieces->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Nephews and Nieces') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->NephewsNieces->allCount): ?>
                    <?php if ($extfam_obj->efp->NephewsNieces->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->NephewsNieces->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one niece recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->NephewsNieces->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one nephew recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one nephew or niece recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->NephewsNieces->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d niece recorded.',  '%2$s has %1$d nieces recorded.', $extfam_obj->efp->NephewsNieces->femaleCount, $extfam_obj->efp->NephewsNieces->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->NephewsNieces->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d nephew recorded.', '%2$s has %1$d nephews recorded.', $extfam_obj->efp->NephewsNieces->maleCount, $extfam_obj->efp->NephewsNieces->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d nephew and ', '%2$s has %1$d nephews and ', $extfam_obj->efp->NephewsNieces->maleCount, $extfam_obj->efp->NephewsNieces->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d niece recorded (%d in total).', '%d nieces recorded (%d in total).', $extfam_obj->efp->NephewsNieces->femaleCount, $extfam_obj->efp->NephewsNieces->femaleCount, $extfam_obj->efp->NephewsNieces->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php foreach ($extfam_obj->efp->NephewsNieces->families as $family): ?>
                            <div id="extended_family_g">
                                <h4><?= I18N::translate(/*'Family with x / Family x and y'*/'') ?></h4>
                                <?php $prev_fam_id = '-1'; ?>
                                <?php $i = 1; ?>
                                <?php  foreach ($extfam_obj->efp->NephewsNieces->families[0]->members as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url()); ?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no nephews or nieces recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>

        <?php if ( $extfam_obj->config->showFamilyPart['children'] ): ?>
            <div class="hh-extended-family-children">
				<?php if (($extfam_obj->efp->Children->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Children') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Children->allCount): ?>
                    <?php if ($extfam_obj->efp->Children->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Children->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one daughter recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Children->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one son recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one child recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Children->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d daughter recorded.',  '%2$s has %1$d daughters recorded.', $extfam_obj->efp->Children->femaleCount, $extfam_obj->efp->Children->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Children->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d son recorded.', '%2$s has %1$d sons recorded.', $extfam_obj->efp->Children->maleCount, $extfam_obj->efp->Children->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d son and ', '%2$s has %1$d sons and ', $extfam_obj->efp->Children->maleCount, $extfam_obj->efp->Children->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d daughter recorded (%d in total).', '%d daughters recorded (%d in total).', $extfam_obj->efp->Children->femaleCount, $extfam_obj->efp->Children->femaleCount, $extfam_obj->efp->Children->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php foreach ($extfam_obj->efp->Children->families as $famobj): ?>
                            <div id="extended_family_g">
                                <?php $prev_fam_id = '-1'; ?>
                                <?php $i = 1; ?>
                                <?php  foreach ($famobj->members as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url());?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no children recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
        
        <?php if ( $extfam_obj->config->showFamilyPart['grandchildren'] ): ?>
            <div class="hh-extended-family-grandchildren">
				<?php if (($extfam_obj->efp->Grandchildren->allCount > 0) or ($extfam_obj->config->showEmptyBlock == 0)): ?>
					<h2><?= I18N::translate('Grandchildren') ?></h2>
				<?php endif ?>
                <?php if ($extfam_obj->efp->Grandchildren->allCount): ?>
                    <?php if ($extfam_obj->efp->Grandchildren->allCount == 1): ?>
                        <?php if ($extfam_obj->efp->Grandchildren->femaleCount == 1): ?>
                            <h3><?= I18N::translate('%s has one granddaughter recorded.', $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Grandchildren->maleCount == 1): ?>
                                <h3><?= I18N::translate('%s has one grandson recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::translate('%s has one grandchild recorded.', $extfam_obj->Self->niceName) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($extfam_obj->efp->Grandchildren->maleCount == 0): ?>
                            <h3><?= I18N::plural('%2$s has %1$d granddaughter recorded.',  '%2$s has %1$d granddaughters recorded.', $extfam_obj->efp->Grandchildren->femaleCount, $extfam_obj->efp->Grandchildren->femaleCount, $extfam_obj->Self->niceName) ?></h3>
                        <?php else: ?>
                            <?php if ($extfam_obj->efp->Grandchildren->femaleCount == 0): ?>
                                <h3><?= I18N::plural('%2$s has %1$d grandson recorded.', '%2$s has %1$d grandsons recorded.', $extfam_obj->efp->Grandchildren->maleCount, $extfam_obj->efp->Grandchildren->maleCount, $extfam_obj->Self->niceName) ?></h3>
                            <?php else: ?>
                                <h3><?= I18N::plural('%2$s has %1$d grandson and ', '%2$s has %1$d grandsons and ', $extfam_obj->efp->Grandchildren->maleCount, $extfam_obj->efp->Grandchildren->maleCount, $extfam_obj->Self->niceName) ?>
                                    <?= I18N::plural('%d granddaughter recorded (%d in total).', '%d granddaughters recorded (%d in total).', $extfam_obj->efp->Grandchildren->femaleCount, $extfam_obj->efp->Grandchildren->femaleCount, $extfam_obj->efp->Grandchildren->allCount) ?></h3>
                            <?php endif ?>
                        <?php endif ?>
                    <?php endif ?>
                    <div id="hh_extended_family_content">
                        <?php foreach ($extfam_obj->efp->Grandchildren->families as $famobj): ?>
                            <div id="extended_family_g">
                                <?php $prev_fam_id = '-1'; ?>
                                <?php $i = 1; ?>
                                <?php  foreach ($famobj->members as $indi) : ?>
                                    <?php if ($indi->childFamilies()->first()->xref() != $prev_fam_id) : ?>
                                        <?php $prev_fam_id = $indi->childFamilies()->first()->xref(); $i = 1; ?>
                                        <h5><?= /* I18N: Do not translate. Already in webtrees core */ I18N::translate('Parents') ?><a href="<?= e($indi->childFamilies()->first()->url());?>">&nbsp;<?= $indi->childFamilies()->first()->fullName(); ?></a></h5>
                                    <?php endif ?>
                                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                                        <span class="extended_family_counter"><?= $i ?> </span>
                                        <?php if ($indi->canShow()): ?>
                                            <span class="extended_family_name"><a href="<?= e($indi->url()) ?>"><?= $indi->fullName() ?></a></span>
                                        <?php else: ?>
                                            <span class="extended_family_name"><?= $indi->fullName() ?></span>
                                        <?php endif ?>
                                        <span class="extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                                    </div>
                                <?php $i++; endforeach ?>
                            </div>    
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
					<?php if ($extfam_obj->config->showEmptyBlock == 0): ?>
						<h3><?= I18N::translate('%s has no grandchildren recorded.', $extfam_obj->Self->niceName) ?></h3>
					<?php endif ?>
                <?php endif ?>
            </div>
        <?php endif ?>
		
        <?php if ($extfam_obj->config->showEmptyBlock == 1) : ?>
            <?php if ($extfam_obj->efp->summaryMessageEmptyBlocks !== '') : ?>
                <div class="hh-extended-family-summary">
                    <h2><?= I18N::translate('Parts of extended family without recorded information') ?></h2>
                    <h3><?= $extfam_obj->efp->summaryMessageEmptyBlocks ?></h3>
                </div>
            <?php endif ?>
		<?php endif ?>
		
    <?php else: ?>
        <h3><?= I18N::translate('No family available') ?></h3>
    <?php endif ?>
</div>

<?php View::push('javascript') ?>
<script>
  var newSheet=document.createElement("link");
  newSheet.setAttribute("rel","stylesheet");
  newSheet.setAttribute("type","text/css");
  newSheet.setAttribute("href","<?= $extended_family_css ?>");
  document.head.appendChild(newSheet);
</script>
<?php View::endpush() ?>
