<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var object $extfam_obj
 * @var object $filterObj
 * @var string $filterOption
 * @var string $propName
 * @var string $summaryName
 */

$familyPart = $filterObj->efp->$propName;
$counts = $familyPart->counts;
$showProbandLabels = in_array($propName, ['parents', 'siblings'], true);

?>

                            <div id="hh-extended-family-summary">
                                <?php if ($propName == 'great_grandparents'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-grandmother recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-grandfather recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one great-grandparent of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandmother recorded.',  '%2$s has %1$d great-grandmothers recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandfather recorded.', '%2$s has %1$d great-grandfathers recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandparent of diverse or unknown sex recorded.', '%2$s has %1$d great-grandparents of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandfather and', '%2$s has %1$d great-grandfathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandmother recorded (%d in total).', '%d great-grandmothers recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandfather and', '%2$s has %1$d great-grandfathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandparent of diverse or unknown sex recorded (%d in total).', '%d great-grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandmother and', '%2$s has %1$d great-grandmothers and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandparent of diverse or unknown sex recorded (%d in total).', '%d great-grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandfather,', '%2$s has %1$d great-grandfathers,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandmother, and', '%d great-grandmothers, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d great-grandparent of diverse or unknown sex recorded (%d in total).', '%d great-grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'grandparents'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandmother recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandfather recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one grandparent of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandmother recorded.',  '%2$s has %1$d grandmothers recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandfather recorded.', '%2$s has %1$d grandfathers recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandparent of diverse or unknown sex recorded.', '%2$s has %1$d grandparents of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandfather and', '%2$s has %1$d grandfathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandmother recorded (%d in total).', '%d grandmothers recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandfather and', '%2$s has %1$d grandfathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandparent of diverse or unknown sex recorded (%d in total).', '%d grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandmother and', '%2$s has %1$d grandmothers and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandparent of diverse or unknown sex recorded (%d in total).', '%d grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandfather,', '%2$s has %1$d grandfathers,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandmother, and', '%d grandmothers, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d grandparent of diverse or unknown sex recorded (%d in total).', '%d grandparents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'grandaunts_uncles'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandaunt recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one granduncle recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one grandaunt or granduncle of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandaunt recorded.',  '%2$s has %1$d grandaunts recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granduncle recorded.', '%2$s has %1$d granduncles recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandaunt or granduncle of diverse or unknown sex recorded.', '%2$s has %1$d grandaunts or granduncles of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granduncle and', '%2$s has %1$d granduncles and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandaunt recorded (%d in total).', '%d grandaunts recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granduncle and', '%2$s has %1$d granduncles and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandaunt or granduncle of diverse or unknown sex recorded (%d in total).', '%d grandaunts or granduncles of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandaunt and', '%2$s has %1$d grandaunts and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandaunt or granduncle of diverse or unknown sex recorded (%d in total).', '%d grandaunts or granduncles of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granduncle,', '%2$s has %1$d granduncles,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandaunt, and', '%d grandaunts, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d grandaunt or granduncle of diverse or unknown sex recorded (%d in total).', '%d grandaunts or granduncles of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'uncles_and_aunts'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one aunt recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one uncle recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one uncle or aunt of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d aunt recorded.',  '%2$s has %1$d aunts recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle recorded.', '%2$s has %1$d uncles recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle or aunt of diverse or unknown sex recorded.', '%2$s has %1$d uncles or aunts of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle and', '%2$s has %1$d uncles and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d aunt recorded (%d in total).', '%d aunts recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle and', '%2$s has %1$d uncles and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d aunt and', '%2$s has %1$d aunts and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle,', '%2$s has %1$d uncles,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d aunt, and', '%d aunts, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'uncles_and_aunts_bm'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one aunt by marriage recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one uncle by marriage recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one uncle or aunt by marriage of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d aunt by marriage recorded.',  '%2$s has %1$d aunts by marriage recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle by marriage recorded.', '%2$s has %1$d uncles by marriage recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle or aunt by marriage of diverse or unknown sex recorded.', '%2$s has %1$d uncles or aunts by marriage of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle by marriage and', '%2$s has %1$d uncles by marriage and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d aunt by marriage recorded (%d in total).', '%d aunts by marriage recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle by marriage and', '%2$s has %1$d uncles by marriage and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt by marriage of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts by marriage of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d aunt by marriage and', '%2$s has %1$d aunts by marriage and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt by marriage of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts by marriage of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d uncle by marriage,', '%2$s has %1$d uncles by marriage,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d aunt by marriage, and', '%d aunts by marriage, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d uncle or aunt by marriage of diverse or unknown sex recorded (%d in total).', '%d uncles or aunts by marriage of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'parents'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one mother recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one father recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one parent of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d mother recorded.',  '%2$s has %1$d mothers recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father recorded.', '%2$s has %1$d fathers recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d parent of diverse or unknown sex recorded.', '%2$s has %1$d parents of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father and', '%2$s has %1$d fathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d mother recorded (%d in total).', '%d mothers recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father and', '%2$s has %1$d fathers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d parent of diverse or unknown sex recorded (%d in total).', '%d parents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d mother and', '%2$s has %1$d mothers and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d parent of diverse or unknown sex recorded (%d in total).', '%d parents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father,', '%2$s has %1$d fathers,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d mother, and', '%d mothers, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d parent of diverse or unknown sex recorded (%d in total).', '%d parents of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($showProbandLabels && $extfam_obj->config->showLabels && $extfam_obj->proband->labels): ?>
                                        <?php foreach ($extfam_obj->proband->labels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                    <?php if ($propName == 'parents' && $extfam_obj->config->showSosaNumbers && $extfam_obj->proband->sosaLabels): ?>
                                        <?php foreach ($extfam_obj->proband->sosaLabels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'parents_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one mother-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one father-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one parent-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d mother-in-law recorded.',  '%2$s has %1$d mothers-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father-in-law recorded.', '%2$s has %1$d fathers-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d parent-in-law of diverse or unknown sex recorded.', '%2$s has %1$d parents-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father-in-law and', '%2$s has %1$d fathers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d mother-in-law recorded (%d in total).', '%d mothers-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father-in-law and', '%2$s has %1$d fathers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d parent-in-law of diverse or unknown sex recorded (%d in total).', '%d parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d mother-in-law and', '%2$s has %1$d mothers-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d parent-in-law of diverse or unknown sex recorded (%d in total).', '%d parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d father-in-law,', '%2$s has %1$d fathers-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d mother-in-law, and', '%d mothers-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d parent-in-law of diverse or unknown sex recorded (%d in total).', '%d parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'co_parents_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one co-mother-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one co-father-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one co-parent-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-mother-in-law recorded.',  '%2$s has %1$d co-mothers-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-father-in-law recorded.', '%2$s has %1$d co-fathers-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-parent-in-law of diverse or unknown sex recorded.', '%2$s has %1$d co-parents-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-father-in-law and', '%2$s has %1$d co-fathers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-mother-in-law recorded (%d in total).', '%d co-mothers-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-father-in-law and', '%2$s has %1$d co-fathers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-parent-in-law of diverse or unknown sex recorded (%d in total).', '%d co-parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-mother-in-law and', '%2$s has %1$d co-mothers-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-parent-in-law of diverse or unknown sex recorded (%d in total).', '%d co-parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-father-in-law,', '%2$s has %1$d co-fathers-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-mother-in-law, and', '%d co-mothers-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d co-parent-in-law of diverse or unknown sex recorded (%d in total).', '%d co-parents-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'partners'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one female partner recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one male partner recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one partner of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($filterObj->efp->$propName->popCount == 0): ?>
                                            <?php if ($counts->femaleCount == $counts->allCount): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d female partner recorded.',  '%2$s has %1$d female partners recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                            <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d male partner recorded.', '%2$s has %1$d male partners recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                            <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d partner of diverse or unknown sex recorded.', '%2$s has %1$d partners of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                            <?php elseif ($counts->otherSexCount == 0): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d female partner recorded (%d in total).', '%d female partners recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                            <?php elseif ($counts->femaleCount == 0): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d partner of diverse or unknown sex recorded (%d in total).', '%d partners of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                            <?php elseif ($counts->maleCount == 0): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d female partner and', '%2$s has %1$d female partners and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d partner of diverse or unknown sex recorded (%d in total).', '%d partners of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                            <?php else: ?>
                                                <h3><?= I18N::plural('%2$s has %1$d male partner,', '%2$s has %1$d male partners,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d female partner, and', '%d female partners, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                    <?= I18N::plural('%d partner of diverse or unknown sex recorded (%d in total).', '%d partners of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                            <?php endif ?>
                                        <?php else: ?>
                                            <?php if ($extfam_obj->proband->indi->sex() == 'M'): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d female partner and', '%2$s has %1$d female partners and', $filterObj->efp->$propName->pfemaleCount, $filterObj->efp->$propName->pfemaleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d male partner of female partners recorded (%d in total).', '%d male partners of female partners recorded (%d in total).', $filterObj->efp->$propName->popmaleCount, $filterObj->efp->$propName->popmaleCount, $counts->allCount) ?>
                                                </h3>
                                            <?php elseif ($extfam_obj->proband->indi->sex() == 'F'): ?>
                                                <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $filterObj->efp->$propName->pmaleCount, $filterObj->efp->$propName->pmaleCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%d female partner of male partners recorded (%d in total).', '%d female partners of male partners recorded (%d in total).', $filterObj->efp->$propName->popfemaleCount, $filterObj->efp->$propName->popfemaleCount, $counts->allCount) ?>
                                                </h3>
                                            <?php else: ?>
                                                <h3><?= I18N::plural('%2$s has %1$d partner and', '%2$s has %1$d partners and', $filterObj->efp->$propName->pCount, $filterObj->efp->$propName->pCount, $summaryName) . ' ' ?>
                                                    <?= I18N::plural('%1$d partner of partners recorded (%2$d in total).', '%1$d partners of partners recorded (%2$d in total).', $filterObj->efp->$propName->popCount, $filterObj->efp->$propName->popCount, $counts->allCount) ?>
                                                </h3>
                                            <?php endif ?>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'partner_chains'): ?>
                                    <?php if ($counts->femaleCount == $counts->allCount): ?>
                                        <h3><?php echo(I18N::plural('%d female partner in this partner chain recorded', '%d female partners in this partner chain recorded', $counts->femaleCount, $counts->femaleCount) .
                                                (($extfam_obj->proband->indi->sex() == 'F')? ' ('.I18N::translate('including %s', $summaryName).')':'') . '.');
                                        ?></h3>
                                    <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                        <h3><?php echo(I18N::plural('%d male partner in this partner chain recorded', '%d male partners in this partner chain recorded', $counts->maleCount, $counts->maleCount) .
                                                (($extfam_obj->proband->indi->sex() == 'M')? ' ('.I18N::translate('including %s', $summaryName).')':'') . '.');
                                        ?></h3>
                                    <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                        <h3><?php echo(I18N::plural('%d partner of diverse or unknown sex in this partner chain recorded', '%d partners of diverse or unknown sex in this partner chain recorded', $counts->otherSexCount, $counts->otherSexCount) .
                                                (($extfam_obj->proband->indi->sex() !== 'M' && $extfam_obj->proband->indi->sex() !== 'F')? ' ('.I18N::translate('including %s', $summaryName).')':'') . '.');
                                        ?></h3>
                                    <?php elseif ($counts->otherSexCount == 0): ?>
                                        <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                            <?php echo(I18N::plural('%1$d female partner in this partner chain recorded (%2$d in total', '%1$d female partners in this partner chain recorded (%2$d in total', $counts->femaleCount, $counts->femaleCount, $counts->allCount) .
                                                (($extfam_obj->proband->indi->sex() === 'M' || $extfam_obj->proband->indi->sex() === 'F')? ', '.I18N::translate('including %s', $summaryName).')':')') . '.');
                                        ?></h3>
                                    <?php elseif ($counts->femaleCount == 0): ?>
                                        <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                            <?php echo(I18N::plural('%1$d partner of diverse or unknown sex in this partner chain recorded (%2$d in total', '%1$d partners of diverse or unknown sex in this partner chain recorded (%2$d in total', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) .
                                                (($extfam_obj->proband->indi->sex() !== 'F')? ', '.I18N::translate('including %s', $summaryName).')':')') . '.');
                                        ?></h3>
                                    <?php elseif ($counts->maleCount == 0): ?>
                                        <h3><?= I18N::plural('%2$s has %1$d female partner and', '%2$s has %1$d female partners and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                            <?php echo(I18N::plural('%1$d partner of diverse or unknown sex in this partner chain recorded (%2$d in total', '%1$d partners of diverse or unknown sex in this partner chain recorded (%2$d in total', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) .
                                                (($extfam_obj->proband->indi->sex() !== 'M')? ', '.I18N::translate('including %s', $summaryName).')':')') . '.');
                                        ?></h3>
                                    <?php else: ?>
                                        <h3><?= I18N::plural('%2$s has %1$d male partner and', '%2$s has %1$d male partners and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                            <?= I18N::plural('%d female partner, and', '%d female partners, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                            <?= I18N::plural('%1$d partner of diverse or unknown sex in this partner chain recorded (%2$d in total, including %3$s).', '%1$d partners of diverse or unknown sex in this partner chain recorded (%2$d in total, including %3$s).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount, $summaryName) ?>
                                        </h3>
                                    <?php endif ?>
                                    <?php if ($filterObj->efp->$propName->chains->chainsCount > 1): ?>
                                        <h3><?= I18N::translate('There are %d branches in the partner chain.', $filterObj->efp->$propName->chains->chainsCount, $filterObj->efp->$propName->chains->chainsCount) . ' ' ?>
                                            <?php if ($filterOption == 'all'): ?>
                                                <?= I18N::translate('The longest branch in the partner chain to %2$s consists of %1$d partners (including %3$s).', $filterObj->efp->$propName->chains->longestChainCount, $filterObj->efp->$propName->chains->mostDistantPartner->fullname(), $summaryName) ?>
                                            <?php else: ?>
                                                <?= I18N::translate('The longest branch in the partner chain consists of %1$d partners (including %2$s).', $filterObj->efp->$propName->chains->longestChainCount, $summaryName) ?>
                                            <?php endif ?>
                                        </h3>
                                    <?php endif ?>
                                <?php elseif ($propName == 'siblings'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one sister recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one brother recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one sibling of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sister recorded.',  '%2$s has %1$d sisters recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother recorded.', '%2$s has %1$d brothers recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sibling of diverse or unknown sex recorded.', '%2$s has %1$d siblings of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother and', '%2$s has %1$d brothers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sister recorded (%d in total).', '%d sisters recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother and', '%2$s has %1$d brothers and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sibling of diverse or unknown sex recorded (%d in total).', '%d siblings of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sister and', '%2$s has %1$d sisters and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sibling of diverse or unknown sex recorded (%d in total).', '%d siblings of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother,', '%2$s has %1$d brothers,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sister, and', '%d sisters, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d sibling of diverse or unknown sex recorded (%d in total).', '%d siblings of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($showProbandLabels && $extfam_obj->config->showLabels && $extfam_obj->proband->labels): ?>
                                        <?php foreach ($extfam_obj->proband->labels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                    <?php if ($propName == 'parents' && $extfam_obj->config->showSosaNumbers && $extfam_obj->proband->sosaLabels): ?>
                                        <?php foreach ($extfam_obj->proband->sosaLabels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'siblings_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one sister-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one brother-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one sibling-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sister-in-law recorded.',  '%2$s has %1$d sisters-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother-in-law recorded.', '%2$s has %1$d brothers-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sibling-in-law of diverse or unknown sex recorded.', '%2$s has %1$d siblings-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother-in-law and', '%2$s has %1$d brothers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sister-in-law recorded (%d in total).', '%d sisters-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother-in-law and', '%2$s has %1$d brothers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d sister-in-law and', '%2$s has %1$d sisters-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d brother-in-law,', '%2$s has %1$d brothers-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d sister-in-law, and', '%d sisters-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($showProbandLabels && $extfam_obj->config->showLabels && $extfam_obj->proband->labels): ?>
                                        <?php foreach ($extfam_obj->proband->labels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                    <?php if ($propName == 'parents' && $extfam_obj->config->showSosaNumbers && $extfam_obj->proband->sosaLabels): ?>
                                        <?php foreach ($extfam_obj->proband->sosaLabels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'co_siblings_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one co-sister-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one co-brother-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one co-sibling-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-sister-in-law recorded.',  '%2$s has %1$d co-sisters-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-brother-in-law recorded.', '%2$s has %1$d co-brothers-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-sibling-in-law of diverse or unknown sex recorded.', '%2$s has %1$d co-siblings-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-brother-in-law and', '%2$s has %1$d co-brothers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-sister-in-law recorded (%d in total).', '%d co-sisters-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-brother-in-law and', '%2$s has %1$d co-brothers-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d co-siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-sister-in-law and', '%2$s has %1$d co-sisters-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d co-siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d co-brother-in-law,', '%2$s has %1$d co-brothers-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d co-sister-in-law, and', '%d co-sisters-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d co-sibling-in-law of diverse or unknown sex recorded (%d in total).', '%d co-siblings-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($showProbandLabels && $extfam_obj->config->showLabels && $extfam_obj->proband->labels): ?>
                                        <?php foreach ($extfam_obj->proband->labels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                    <?php if ($propName == 'parents' && $extfam_obj->config->showSosaNumbers && $extfam_obj->proband->sosaLabels): ?>
                                        <?php foreach ($extfam_obj->proband->sosaLabels as $label): ?>
                                            <span class="hh_extended_family_label"><?= $label ?></span>&nbsp;
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'cousins'): ?>								
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one female first cousin recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one male first cousin recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one first cousin of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d female first cousin recorded.',  '%2$s has %1$d female first cousins recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d male first cousin recorded.', '%2$s has %1$d male first cousins recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d first cousin of diverse or unknown sex recorded.', '%2$s has %1$d first cousins of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d male first cousin and', '%2$s has %1$d male first cousins and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d female first cousin recorded (%d in total).', '%d female first cousins recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d male first cousin and', '%2$s has %1$d male first cousins and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d first cousin of diverse or unknown sex recorded (%d in total).', '%d first cousins of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d female first cousin and', '%2$s has %1$d female first cousins and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d first cousin of diverse or unknown sex recorded (%d in total).', '%d first cousins of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d male first cousin,', '%2$s has %1$d male first cousins,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d female first cousin, and', '%d female first cousins, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d first cousin of diverse or unknown sex recorded (%d in total).', '%d first cousins of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'nephews_and_nieces'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one niece recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one nephew recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one nephew or niece of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d niece recorded.',  '%2$s has %1$d nieces recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d nephew recorded.', '%2$s has %1$d nephews recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d nephew or niece of diverse or unknown sex recorded.', '%2$s has %1$d nephews or nieces of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d nephew and', '%2$s has %1$d nephews and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d niece recorded (%d in total).', '%d nieces recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d nephew and', '%2$s has %1$d nephews and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d nephew or niece of diverse or unknown sex recorded (%d in total).', '%d nephews or nieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d niece and', '%2$s has %1$d nieces and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d nephew or niece of diverse or unknown sex recorded (%d in total).', '%d nephews or nieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d nephew,', '%2$s has %1$d nephews,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d niece, and', '%d nieces, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d nephew or niece of diverse or unknown sex recorded (%d in total).', '%d nephews or nieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'grandnephews_nieces'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandniece recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandnephew recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one grandnephew or grandniece of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandniece recorded.',  '%2$s has %1$d grandnieces recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandnephew recorded.', '%2$s has %1$d grandnephews recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandnephew or grandniece of diverse or unknown sex recorded.', '%2$s has %1$d grandnephews or grandnieces of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandnephew and', '%2$s has %1$d grandnephews and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandniece recorded (%d in total).', '%d grandnieces recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandnephew and', '%2$s has %1$d grandnephews and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandnephew or grandniece of diverse or unknown sex recorded (%d in total).', '%d grandnephews or grandnieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandniece and', '%2$s has %1$d grandnieces and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandnephew or grandniece of diverse or unknown sex recorded (%d in total).', '%d grandnephews or grandnieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandnephew,', '%2$s has %1$d grandnephews,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandniece, and', '%d grandnieces, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d grandnephew or grandniece of diverse or unknown sex recorded (%d in total).', '%d grandnephews or grandnieces of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'children'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one daughter recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one son recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one child of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d daughter recorded.',  '%2$s has %1$d daughters recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son recorded.', '%2$s has %1$d sons recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d child of diverse or unknown sex recorded.', '%2$s has %1$d children of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son and', '%2$s has %1$d sons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d daughter recorded (%d in total).', '%d daughters recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son and', '%2$s has %1$d sons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d child of diverse or unknown sex recorded (%d in total).', '%d children of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d daughter and', '%2$s has %1$d daughters and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d child of diverse or unknown sex recorded (%d in total).', '%d children of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son,', '%2$s has %1$d sons,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d daughter, and', '%d daughters, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d child of diverse or unknown sex recorded (%d in total).', '%d children of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'children_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one daughter-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one son-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one child-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d daughter-in-law recorded.',  '%2$s has %1$d daughters-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son-in-law recorded.', '%2$s has %1$d sons-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d child-in-law of diverse or unknown sex recorded.', '%2$s has %1$d children-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son-in-law and', '%2$s has %1$d sons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d daughter-in-law recorded (%d in total).', '%d daughters-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son-in-law and', '%2$s has %1$d sons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d child-in-law of diverse or unknown sex recorded (%d in total).', '%d children-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d daughter-in-law and', '%2$s has %1$d daughters-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d child-in-law of diverse or unknown sex recorded (%d in total).', '%d children-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d son-in-law,', '%2$s has %1$d sons-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d daughter-in-law, and', '%d daughters-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d child-in-law of diverse or unknown sex recorded (%d in total).', '%d children-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'grandchildren'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one granddaughter recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandson recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one grandchild of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granddaughter recorded.',  '%2$s has %1$d granddaughters recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson recorded.', '%2$s has %1$d grandsons recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandchild of diverse or unknown sex recorded.', '%2$s has %1$d grandchildren of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson and', '%2$s has %1$d grandsons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d granddaughter recorded (%d in total).', '%d granddaughters recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson and', '%2$s has %1$d grandsons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandchild of diverse or unknown sex recorded (%d in total).', '%d grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granddaughter and', '%2$s has %1$d granddaughters and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandchild of diverse or unknown sex recorded (%d in total).', '%d grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson,', '%2$s has %1$d grandsons,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d granddaughter, and', '%d granddaughters, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d grandchild of diverse or unknown sex recorded (%d in total).', '%d grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'great_grandchildren'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-granddaughter recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-grandson recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one great-grandchild of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-granddaughter recorded.',  '%2$s has %1$d great-granddaughters recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson recorded.', '%2$s has %1$d great-grandsons recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandchild of diverse or unknown sex recorded.', '%2$s has %1$d great-grandchildren of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson and', '%2$s has %1$d great-grandsons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-granddaughter recorded (%d in total).', '%d great-granddaughters recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson and', '%2$s has %1$d great-grandsons and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-granddaughter and', '%2$s has %1$d great-granddaughters and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson,', '%2$s has %1$d great-grandsons,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-granddaughter, and', '%d great-granddaughters, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'grandchildren_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one granddaughter-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one grandson-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one grandchild-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granddaughter-in-law recorded.',  '%2$s has %1$d granddaughters-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson-in-law recorded.', '%2$s has %1$d grandsons-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandchild-in-law of diverse or unknown sex recorded.', '%2$s has %1$d grandchildren-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson-in-law and', '%2$s has %1$d grandsons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d granddaughter-in-law recorded (%d in total).', '%d granddaughters-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson-in-law and', '%2$s has %1$d grandsons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d granddaughter-in-law and', '%2$s has %1$d granddaughters-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d grandson-in-law,', '%2$s has %1$d grandsons-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d granddaughter-in-law, and', '%d granddaughters-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                            <?= I18N::plural('%d grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php elseif ($propName == 'godparents_witnesses'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <h3><?= I18N::translate('The extended family of %s has one godparent, witness, or other linked person recorded.', $summaryName) ?></h3>
                                    <?php else: ?>
                                        <h3><?= I18N::plural('The extended family of %2$s has %1$d godparent, witness, or other linked person recorded.', 'The extended family of %2$s has %1$d godparents, witnesses, or other linked persons recorded.', $counts->allCount, $counts->allCount, $summaryName) ?></h3>
                                    <?php endif ?>
                                <?php elseif ($propName == 'great_grandchild_in_law'): ?>
                                    <?php if ($counts->allCount == 1): ?>
                                        <?php if ($counts->femaleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-granddaughter-in-law recorded.', $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == 1): ?>
                                            <h3><?= I18N::translate('%s has one great-grandson-in-law recorded.', $summaryName) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::translate('%s has one great-grandchild-in-law of diverse or unknown sex recorded.', $summaryName) ?></h3>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php if ($counts->femaleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-granddaughter-in-law recorded.',  '%2$s has %1$d great-granddaughters-in-law recorded.', $counts->femaleCount, $counts->femaleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->maleCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson-in-law recorded.', '%2$s has %1$d great-grandsons-in-law recorded.', $counts->maleCount, $counts->maleCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == $counts->allCount): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandchild-in-law of diverse or unknown sex recorded.', '%2$s has %1$d great-grandchildren-in-law of diverse or unknown sex recorded.', $counts->otherSexCount, $counts->otherSexCount, $summaryName) ?></h3>
                                        <?php elseif ($counts->otherSexCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson-in-law and', '%2$s has %1$d great-grandsons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-granddaughter-in-law recorded (%d in total).', '%d great-granddaughters-in-law recorded (%d in total).', $counts->femaleCount, $counts->femaleCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->femaleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson-in-law and', '%2$s has %1$d great-grandsons-in-law and', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php elseif ($counts->maleCount == 0): ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-granddaughter-in-law and', '%2$s has %1$d great-granddaughters-in-law and', $counts->femaleCount, $counts->femaleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php else: ?>
                                            <h3><?= I18N::plural('%2$s has %1$d great-grandson-in-law,', '%2$s has %1$d great-grandsons-in-law,', $counts->maleCount, $counts->maleCount, $summaryName) . ' ' ?>
                                                <?= I18N::plural('%d great-granddaughter-in-law, and', '%d great-granddaughters-in-law, and', $counts->femaleCount, $counts->femaleCount) . ' ' ?>
                                                <?= I18N::plural('%d great-grandchild-in-law of diverse or unknown sex recorded (%d in total).', '%d great-grandchildren-in-law of diverse or unknown sex recorded (%d in total).', $counts->otherSexCount, $counts->otherSexCount, $counts->allCount) ?></h3>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php endif ?>
                            </div>
