<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Grandchildren;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Nephews_and_nieces;

/**
 * @var object $coreLabels
 * @var object $group
 * @var int    $i
 * @var int    $key
 * @var string $prev_id
 */

?>

                        <?php $referencePerson = $entry->referencePersons[1] ?? null ?>
                        <?php if ($referencePerson instanceof Individual && $referencePerson->xref() != $prev_id): ?>
                            <?php $prev_id = $referencePerson->xref(); $i = 1; ?>
                            <?php if ($referencePerson->canShow()): ?>
                                <?php if ($group->groupName == 'Partners of biological children'): ?>
                                    <?php if ($referencePerson->sex() == 'M'): ?>
                                        <h5><?= $coreLabels->son ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php elseif ($referencePerson->sex() == 'F'): ?>
                                        <h5><?= $coreLabels->daughter ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php else: ?>
                                        <h5><?= $coreLabels->child ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php endif ?>
                                <?php elseif ($group->groupName == 'Partners of social children'): ?>
                                    <h5><?= I18N::translate('Social child') ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                <?php elseif ($group->groupName == 'Partners of stepchildren'): ?>
                                    <?php if ($referencePerson->sex() == 'M'): ?>
                                        <h5><?= I18N::translate('Stepson') ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php elseif ($referencePerson->sex() == 'F'): ?>
                                        <h5><?= I18N::translate('Stepdaughter') ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php else: ?>
                                        <h5><?= I18N::translate('Stepchild') ?><a href="<?= e($referencePerson->url()); ?>">&nbsp;<?= $referencePerson->fullName(); ?></a></h5>
                                    <?php endif ?>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if ($group->groupName == 'Partners of biological children'): ?>
                                    <h5><?= $coreLabels->child ?>&nbsp;<?= $referencePerson->fullName() ?></h5>
                                <?php elseif ($group->groupName == 'Partners of social children'): ?>
                                    <h5><?= I18N::translate('Social child')?>&nbsp;<?= $referencePerson->fullName() ?></h5>
                                <?php elseif ($group->groupName == 'Partners of stepchildren'): ?>
                                    <h5><?= I18N::translate('Stepchild')?>&nbsp;<?= $referencePerson->fullName() ?></h5>
                                <?php endif ?>
                            <?php endif ?>
                        <?php endif ?>
