<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Grandchildren;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Nephews_and_nieces;

/**
 * @var object $group
 * @var int    $i
 * @var int    $key
 * @var string $prev_id
 */

?>

                        <?php $referencePerson = $entry->referencePersons[1] ?? null ?>
                        <?php $family = $entry->family ?>
                        <?php if ($referencePerson instanceof Individual && $referencePerson->xref() != $prev_id): ?>
                            <?php $prev_id = $referencePerson->xref(); $i = 1; ?>
                            <?php if ($referencePerson->canShow()): ?>
                                <?php $linkReferencePerson = ('<a href="'.e($referencePerson->url()).'">'.$referencePerson->fullName().'</a>') ?>
                                <?php if ($group->groupName == 'Siblings of siblings-in-law'): ?>
                                    <?php $linkFamily = '<a href="'.e($family->url()).'">'.$family->fullName().'</a>' ?>
                                    <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($entry->familyStatus) ?>
                                    <h5><?= I18N::translate('%1$s %2$s connected with %3$s', $familyStatus, $linkFamily, $linkReferencePerson) ?></h5>
                                <?php else: ?>
                                    <h5><?= I18N::translate('Partners of %s', $linkReferencePerson) ?></h5>
                                <?php endif ?>
                            <?php else: ?>
                                <?php if ($group->groupName == 'Siblings of siblings-in-law'): ?>
                                    <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($entry->familyStatus) ?>
                                    <h5><?= I18N::translate('%1$s %2$s connected with %3$s', $familyStatus, $family->fullName(), $referencePerson->fullName()) ?></h5>
                                <?php else: ?>
                                    <h5><?= I18N::translate('Partners of %s', $referencePerson->fullName()) ?></h5>
                                <?php endif ?>
                            <?php endif ?>
                        <?php endif ?>
