<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Grandchildren;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Nephews_and_nieces;

/**
 * @var object     $group
 * @var int        $i
 * @var Individual $individual
 * @var int        $key
 * @var string     $prev_id
 * @var string     $prev_id1
 * @var string     $prev_id2
 */

?>

                        <?php if ($group->referencePersons[$key][1]->xref() != $prev_id1 || $group->families[$key]->xref() != $prev_id || (isset($group->referencePersons[$key][2]) && ($group->referencePersons[$key][2]->xref() != $prev_id2))): ?>
                            <?php $prev_id1 = $group->referencePersons[$key][1]->xref(); $prev_id = $group->families[$key]->xref(); $i = 1; ?>
                            <?php if ($group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_SIBLING || $group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_PARTNER_SIBLING): ?>
                                <?php $siblingLabel = ExtendedFamilySupport::translateSiblingLabel($group->referencePersons[$key][1], $individual) ?>
                                <?php $linkReferencePerson = ExtendedFamilySupport::individualLink($group->referencePersons[$key][1]) ?>
                                <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($group->familiesStatus[$key]) ?>
                                <?php $linkPartner = ExtendedFamilySupport::partnerInFamilyLink($group->families[$key], $group->referencePersons[$key][1]) ?>
                                <h5><?= I18N::translate('%1$s %2$s, %3$s with %4$s', $siblingLabel, $linkReferencePerson, $familyStatus, $linkPartner) ?></h5>
                            <?php elseif ($group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_SIBLING_PARTNER): ?>
                                <?php $prev_id2 = $group->referencePersons[$key][2]->xref(); ?>
                                <?php $siblingLabel = ExtendedFamilySupport::translateSiblingLabel($group->referencePersons[$key][2], $group->referencePersons[$key][1]) ?>
                                <?php $linkReferencePerson = ExtendedFamilySupport::individualLink($group->referencePersons[$key][1]) ?>
                                <?php $linkReferencePerson2 = ExtendedFamilySupport::individualLink($group->referencePersons[$key][2]) ?>
                                <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($group->familiesStatus[$key]) ?>
                                <?php $linkPartner = ExtendedFamilySupport::partnerInFamilyLink($group->families[$key], $group->referencePersons[$key][2]) ?>
                                <h5><?= I18N::translate('%1$s %2$s of partner %3$s, %4$s with %5$s', $siblingLabel, $linkReferencePerson2, $linkReferencePerson, $familyStatus, $linkPartner) ?></h5>
                            <?php endif ?>
                        <?php endif ?>
