<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Grandchildren;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Nephews_and_nieces;

/**
 * @var object     $group
 * @var int        $i
 * @var Individual $individual
 * @var int        $key
 * @var string     $prev_id
 * @var string     $prev_id1
 * @var string     $prev_id2
 */

?>

                        <?php $referencePerson = $entry->referencePersons[1] ?? null ?>
                        <?php $referencePerson2 = $entry->referencePersons[2] ?? null ?>
                        <?php $family = $entry->family ?>
                        <?php if ($referencePerson instanceof Individual && $family instanceof Family && ($referencePerson->xref() != $prev_id1 || $family->xref() != $prev_id || ($referencePerson2 instanceof Individual && $referencePerson2->xref() != $prev_id2))): ?>
                            <?php $prev_id1 = $referencePerson->xref(); $prev_id = $family->xref(); $i = 1; ?>
                            <?php if ($group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_SIBLING || $group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_PARTNER_SIBLING): ?>
                                <?php $siblingLabel = ExtendedFamilySupport::translateSiblingLabel($referencePerson, $individual) ?>
                                <?php $linkReferencePerson = ExtendedFamilySupport::individualLink($referencePerson) ?>
                                <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($entry->familyStatus) ?>
                                <?php $linkPartner = ExtendedFamilySupport::partnerInFamilyLink($family, $referencePerson) ?>
                                <h5><?= I18N::translate('%1$s %2$s, %3$s with %4$s', $siblingLabel, $linkReferencePerson, $familyStatus, $linkPartner) ?></h5>
                            <?php elseif ($group->groupName == Nephews_and_nieces::GROUP_NEPHEW_NIECES_CHILD_SIBLING_PARTNER && $referencePerson2 instanceof Individual): ?>
                                <?php $prev_id2 = $referencePerson2->xref(); ?>
                                <?php $siblingLabel = ExtendedFamilySupport::translateSiblingLabel($referencePerson2, $referencePerson) ?>
                                <?php $linkReferencePerson = ExtendedFamilySupport::individualLink($referencePerson) ?>
                                <?php $linkReferencePerson2 = ExtendedFamilySupport::individualLink($referencePerson2) ?>
                                <?php $familyStatus = ExtendedFamilySupport::translateFamilyStatus($entry->familyStatus) ?>
                                <?php $linkPartner = ExtendedFamilySupport::partnerInFamilyLink($family, $referencePerson2) ?>
                                <h5><?= I18N::translate('%1$s %2$s of partner %3$s, %4$s with %5$s', $siblingLabel, $linkReferencePerson2, $linkReferencePerson, $familyStatus, $linkPartner) ?></h5>
                            <?php endif ?>
                        <?php endif ?>
