<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Grandchildren;
use Hartenthaler\Webtrees\Module\ExtendedFamily\Nephews_and_nieces;

/**
 * @var object     $coreLabels
 * @var object     $extfam_obj
 * @var object     $filterObj
 * @var Individual $individual
 * @var string     $propName
 */

?>

        <?php foreach ($filterObj->efp->$propName->groups as $group): ?>
            <div class="hh_extended_family_box">
                <h4><?= ExtendedFamilySupport::translateGroupName($group->groupName); ?>&nbsp;(<?= count($group->entries) ?>)</h4>
                <?php $prev_id = -1; $prev_id1 = -1; $prev_id2 = -1; ?>
                <?php  foreach ($group->entries as $key => $entry) : ?>
                    <?php $indi = $entry->individual; ?>
                    <?php if ($propName == 'siblings_in_law' || $propName == 'uncles_and_aunts_bm') : ?>
                        <?php include __DIR__ . '/grouped-headings/reference-person.phtml'; ?>
                    <?php elseif ($propName == 'nephews_and_nieces') : ?>
                        <?php include __DIR__ . '/grouped-headings/nephews-and-nieces.phtml'; ?>
                    <?php elseif ($propName == 'children_in_law'): ?>
                        <?php include __DIR__ . '/grouped-headings/children-in-law.phtml'; ?>
                    <?php elseif ($propName == 'great_grandparents' || $propName == 'grandparents' || $propName == 'grandaunts_uncles' || $propName == 'uncles_and_aunts' || $propName == 'parents' || $propName == 'ex_partners_of_parents' || $propName == 'co_parents_in_law' || $propName == 'grandchildren_in_law' || $propName == 'great_grandchild_in_law'): ?>
                        <?php include __DIR__ . '/grouped-headings/family-reference.phtml'; ?>
                    <?php elseif ($propName == 'co_siblings_in_law'): ?>
                        <?php include __DIR__ . '/grouped-headings/co-siblings-in-law.phtml'; ?>
                    <?php elseif ($propName == 'siblings' || $propName == 'cousins' || $propName == 'grandnephews_nieces' || $propName == 'children' || $propName == 'grandchildren' || $propName == 'great_grandchildren'): ?>
                        <?php include __DIR__ . '/grouped-headings/child-family.phtml'; ?>
                    <?php endif ?>
                    <?php include __DIR__ . '/../person-box.phtml'; ?>
                <?php $i++; endforeach ?>
            </div>
        <?php endforeach ?>
