<?php

use Fisharebest\Webtrees\I18N;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;

/**
 * @var object $extfam_obj
 * @var object $filterObj
 * @var string $propName
 */

?>

        <?php foreach ($filterObj->efp->$propName->groups as $key => $group): ?>
            <div class="hh_extended_family_box">
                <h4><?= I18N::translate('Partner of') . ' ' ?>
                    <?php if ($group->partner->xref() == $extfam_obj->proband->indi->xref()): ?>
                        <?= $extfam_obj->proband->niceName->plain ?>
                    <?php else: ?>
                        <?php $relationshipName = $extfam_obj->config->showRelationshipToProband ? ExtendedFamilySupport::relationshipNameToProband($group->partner, $extfam_obj->proband->indi) : '' ?>
                        <span class="hh_extended_family_name"><?= ExtendedFamilySupport::individualLink($group->partner, $relationshipName) ?></span>
                    <?php endif ?>
                    &nbsp;(<?= count($group->entries) ?>)
                </h4>
                <?php $i = 1; ?>
                <?php foreach ($group->entries as $key => $entry) : ?>
                    <?php $indi = $entry->individual; ?>
                    <?php include __DIR__ . '/grouped-headings/partners.phtml'; ?>
                    <?php include __DIR__ . '/../person-box.phtml'; ?>
                <?php $i++; endforeach ?>
            </div>    
        <?php endforeach ?>
