<?php

use Fisharebest\Webtrees\I18N;
use Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport;

/**
 * @var object $extfam_obj
 * @var object $filterObj
 * @var string $propName
 */

?>

        <?php foreach ($filterObj->efp->$propName->groups as $key => $group): ?>
            <div class="hh_extended_family_box">
                <h4><?= I18N::translate('Partner of') . ' ' ?>
                    <?php if ($group->partner->xref() == $extfam_obj->proband->indi->xref()): ?>
                        <?= $extfam_obj->proband->niceName->plain ?>
                    <?php else: ?>
                        <?php $relationshipName = $extfam_obj->config->showRelationshipToProband ? ExtendedFamilySupport::relationshipNameToProband($group->partner, $extfam_obj->proband->indi) : '' ?>
                        <span class="hh_extended_family_name"><?= ExtendedFamilySupport::individualLink($group->partner, $relationshipName) ?></span>
                    <?php endif ?>
                    &nbsp;(<?= count($group->entries) ?>)
                </h4>
                <?php $i = 1; ?>
                <?php foreach ($group->entries as $key => $entry) : ?>
                    <?php $indi = $entry->individual; ?>
                    <?php include __DIR__ . '/grouped-headings/partners.phtml'; ?>
                    <div class="wt-chart-box-<?= strtolower($indi->sex()) ?>">
                        <?php if ($indi->canShow()): ?>
                            <?php if ($extfam_obj->config->showThumbnail): ?>
                                <div class="wt-chart-box-thumbnail float-start mr-1" style="--hh-thumbnail-width: <?= $extfam_obj->config->sizeThumbnailW ?>px; --hh-thumbnail-height: <?= $extfam_obj->config->sizeThumbnailH ?>px;"><?= $indi->displayImage($extfam_obj->config->sizeThumbnailW, $extfam_obj->config->sizeThumbnailH, 'crop', ['class' => 'wt-chart-box-thumbnail']) ?></div>
                            <?php endif ?>
                            <span class="hh_extended_family_counter"><?= $i ?></span>
                            <?php $relationshipName = $extfam_obj->config->showRelationshipToProband ? ExtendedFamilySupport::relationshipNameToProband($indi, $extfam_obj->proband->indi) : '' ?>
                            <span class="hh_extended_family_name"><?= ExtendedFamilySupport::individualLink($indi, $relationshipName) ?></span>
                            <?php if ($extfam_obj->config->showLabels && $entry->labels): ?>
                                <?php foreach ($entry->labels as $label): ?>
                                    <span class="hh_extended_family_label_box"><?= $label ?></span>&nbsp;
                                <?php endforeach ?>
                            <?php endif ?>
                            <?php if ($extfam_obj->config->showSosaNumbers && $entry->sosaLabels): ?>
                                <?php foreach ($entry->sosaLabels as $label): ?>
                                    <span class="hh_extended_family_label_box"><?= $label ?></span>&nbsp;
                                <?php endforeach ?>
                            <?php endif ?>
                            <?php if ($extfam_obj->config->useCompactDesign): ?>
                                <span class="hh_extended_family_lifespan" ><?= $indi->lifespan() ?></span>
                            <?php else: ?>
                                <span class="hh_extended_family_birth_death">
                                    <?= $entry->vitalEventsSummary ?>
                                </span>
                            <?php endif ?>
                        <?php else: ?>
                            <span class="hh_extended_family_name"><?= ExtendedFamilySupport::individualName($indi) ?></span>
                        <?php endif ?>
                    </div>
                <?php $i++; endforeach ?>
            </div>    
        <?php endforeach ?>
